### PR TITLE
MVN Release deployment

### PR DESCRIPTION
**Pull request by Anrufliste**
- [x] Update used PhoneLib version to latest (8.13.11)
- [x] Create automatic release artifact
- [ ] Publish Artifact to Maven Central

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, I am not sure if this is really what you expect.
The description says:
"Create automatic publishing of release to MVN repository" - my assumption was that we both talked about Maven Central here, so that the library becomes publicly available to everyone easily.

This PR here seems to only introduce the Maven Release plugin and automate the release process on the source code, i.e. bumping versions etc. But it definitely won't deploy binary artifacts to Maven Central...

**Comment by Anrufliste** [comment]
> Hm, I am not sure if this is really what you expect. The description says: "Create automatic publishing of release to MVN repository" - my assumption was that we both talked about Maven Central here, so that the library becomes publicly available to everyone easily.
> 
> This PR here seems to only introduce the Maven Release plugin and automate the release process on the source code, i.e. bumping versions etc. But it definitely won't deploy binary artifacts to Maven Central...

sorry - I did to much find & replace ... configuration should make a real artifact (not just pack the code into ZIP) ... if that works, next step would be to bring it to maven central (you are completely right - added new todo to the PR)

**Comment by Anrufliste** [comment]
Next step is guided by
https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c and

**Comment by Anrufliste** [comment]
Not necessary - will use another approach and a separate pr for phone lib version update.

**Pull request closed without merging**
